use clap::{Args, Subcommand};
use std::path::Path;

#[derive(Args)]
pub struct MountArgs {
    #[command(subcommand)]
    pub command: MountCommand,
}

#[derive(Subcommand)]
pub enum MountCommand {
    /// Inject semantic agent into debug builds (no code changes needed)
    Semantic(SemanticArgs),
}

#[derive(Args)]
pub struct SemanticArgs {
    /// Project root (default: current directory)
    #[arg(long, default_value = ".")]
    pub project: String,
}

pub fn run(args: MountArgs) -> Result<(), String> {
    match args.command {
        MountCommand::Semantic(a) => mount_semantic(&a.project),
    }
}

pub fn unmount(args: MountArgs) -> Result<(), String> {
    match args.command {
        MountCommand::Semantic(a) => unmount_semantic(&a.project),
    }
}

const AGENT_LIB_PATH: &str = "/Users/Shared/projects/substrate-distro/device-control-android/semantic-agent";

fn mount_semantic(project: &str) -> Result<(), String> {
    let project = Path::new(project);

    // Copy agent source files into app/src/debug/java/dev/substrate/semantic/
    let debug_src = project.join("app/src/debug/java/dev/substrate/semantic");
    std::fs::create_dir_all(&debug_src)
        .map_err(|e| format!("create debug src dir: {e}"))?;

    let agent_src = Path::new(AGENT_LIB_PATH).join("src/main/java/dev/substrate/semantic");
    for filename in &[
        "SemanticElement.kt",
        "SemanticServer.kt",
        "ViewTreeWalker.kt",
        "SemanticInitProvider.kt",
    ] {
        let src = agent_src.join(filename);
        let dst = debug_src.join(filename);
        std::fs::copy(&src, &dst)
            .map_err(|e| format!("copy {filename}: {e}"))?;
    }

    // Copy debug AndroidManifest with ContentProvider registration
    let debug_manifest_dir = project.join("app/src/debug");
    let agent_manifest = Path::new(AGENT_LIB_PATH).join("src/main/AndroidManifest.xml");
    let dst_manifest = debug_manifest_dir.join("AndroidManifest.xml");
    if !dst_manifest.exists() {
        std::fs::copy(&agent_manifest, &dst_manifest)
            .map_err(|e| format!("copy manifest: {e}"))?;
    }

    // Add nanohttpd dependency via init script
    let init_dir = project.join(".gradle/init.d");
    std::fs::create_dir_all(&init_dir)
        .map_err(|e| format!("create init dir: {e}"))?;

    let init_script = init_dir.join("semantic-agent.gradle.kts");
    let script = r#"// Auto-generated by ddb mount semantic — do not edit
allprojects {
    afterEvaluate {
        if (plugins.hasPlugin("com.android.application")) {
            dependencies {
                add("debugImplementation", "org.nanohttpd:nanohttpd:2.3.1")
            }
        }
    }
}
"#;

    std::fs::write(&init_script, script)
        .map_err(|e| format!("write init script: {e}"))?;

    eprintln!("mounted semantic agent:");
    eprintln!("  source: {}", debug_src.display());
    eprintln!("  manifest: {}", dst_manifest.display());
    eprintln!("  init script: {}", init_script.display());
    eprintln!("rebuild debug APK to activate (./gradlew assembleDebug)");

    Ok(())
}

fn unmount_semantic(project: &str) -> Result<(), String> {
    let project = Path::new(project);

    // Remove source files
    let debug_src = project.join("app/src/debug/java/dev/substrate/semantic");
    if debug_src.exists() {
        std::fs::remove_dir_all(&debug_src)
            .map_err(|e| format!("remove source: {e}"))?;
    }

    // Remove init script
    let init_script = project.join(".gradle/init.d/semantic-agent.gradle.kts");
    if init_script.exists() {
        std::fs::remove_file(&init_script)
            .map_err(|e| format!("remove init script: {e}"))?;
    }

    eprintln!("unmounted semantic agent");
    eprintln!("rebuild to remove (./gradlew assembleDebug)");

    Ok(())
}

